"""
Django settings for sentieri project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h2aio&c_8$^#h^$g7z%7&r3y9&q8vl-q*&#0ei3$-2(_g$t%&&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#EASY_MAPS_GOOGLE_KEY = 'AIzaSyAVgGs3qCV0tF2-6eOgGKOE0rk72_XckiQ' #padre
#EASY_MAPS_GOOGLE_KEY = 'AIzaSyB1gP8tKPgDPWcew7_nqTt_caqfZ4BiH80' #vezz
EASY_MAPS_GOOGLE_KEY = 'AIzaSyAMNPUCgZH_ZvSPDW6pn7GVR_uA3YnAXQk'
#GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyB1gP8tKPgDPWcew7_nqTt_caqfZ4BiH80'
GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyAMNPUCgZH_ZvSPDW6pn7GVR_uA3YnAXQk'

EASY_MAPS_ZOOM = 16
EASY_MAPS_LANGUAGE = 'it'

GEOPOSITION_MAP_OPTIONS = {
    'minZoom': 3,
    'maxZoom': 15,
}

GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move'
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sentieriApp',
    'easy_maps',
    "geoposition",
    'django.contrib.admin'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sentieri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sentieri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# 1. python manage.py dumpdata > db.json
# 2. Change the database settings to new database such as of MySQL / PostgreSQL.
# 3. python manage.py migrate
# 4. python manage.py shell
#   Enter the following in the shell
#   from django.contrib.contenttypes.models import ContentType
#   ContentType.objects.all().delete()
# 5. python manage.py loaddata db.json

DATABASES = {
"default": {
    "ENGINE": "django.db.backends.postgresql_psycopg2",
    "NAME": "sentieri",
    "USER": "postg_django",
    "PASSWORD": "django",
    "HOST": "localhost",
    "PORT": "5432",  # default port
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom user model
AUTH_USER_MODEL = "sentieriApp.Utente"


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/sentieriApp/'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/sentieri'

