# Generated by Django 2.2.1 on 2019-05-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descrizione', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Nazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Nazione',
                'verbose_name_plural': 'Nazioni',
                'db_table': 'nazione',
            },
        ),
        migrations.CreateModel(
            name='PuntoGeografico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudine', models.CharField(max_length=10)),
                ('longitudine', models.CharField(max_length=10)),
                ('altitudine', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('descrizione', models.TextField()),
                ('meteo', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Punto Geografico',
                'verbose_name_plural': 'Punti Geografici',
                'db_table': 'punto_geografico',
            },
        ),
        migrations.CreateModel(
            name='Sentiero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=30)),
                ('descrizione', models.TextField()),
                ('lunghezza', models.FloatField()),
                ('salita', models.IntegerField()),
                ('discesa', models.IntegerField()),
                ('altitudineMax', models.IntegerField()),
                ('altitudineMin', models.IntegerField()),
                ('visite', models.IntegerField(default=0)),
                ('ciclico', models.BooleanField(default=False)),
                ('linkMappa', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Sentiero',
                'verbose_name_plural': 'Sentieri',
                'db_table': 'sentiero',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField()),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Voti',
                'db_table': 'voto',
            },
        ),
        migrations.CreateModel(
            name='Tappa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_geografico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.PuntoGeografico')),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Tappa',
                'verbose_name_plural': 'Tappe',
                'db_table': 'tappa',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Categoria')),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Luogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Luogo',
                'verbose_name_plural': 'Luoghi',
                'db_table': 'luogo',
            },
        ),
        migrations.CreateModel(
            name='Interessi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Categoria')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interessi',
                'db_table': 'interesse',
            },
        ),
        migrations.CreateModel(
            name='Effettuato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Effettuato',
                'verbose_name_plural': 'Effettuati',
                'db_table': 'effettuato',
            },
        ),
        migrations.CreateModel(
            name='Difficolta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField()),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Difficoltà',
                'verbose_name_plural': 'Difficoltà',
                'db_table': 'difficolta',
            },
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('testo', models.TextField()),
                ('sentiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Sentiero')),
            ],
            options={
                'verbose_name': 'Commento',
                'verbose_name_plural': 'Commenti',
                'db_table': 'commento',
            },
        ),
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('id_nazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Nazione')),
            ],
            options={
                'verbose_name': 'Nazione',
                'verbose_name_plural': 'Nazioni',
                'db_table': 'citta',
            },
        ),
    ]
