# Generated by Django 2.2.1 on 2019-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentieriApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiero',
            name='lunghezza',
        ),
        migrations.AddField(
            model_name='sentiero',
            name='dislivello',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sentiero',
            name='titolo',
            field=models.CharField(max_length=50),
        ),
    ]
