# Generated by Django 2.2.1 on 2019-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentieriApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esperienzapersonale',
            name='difficolta',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
