# Generated by Django 2.2.1 on 2019-06-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentieriApp', '0002_esperienzapersonale_difficolta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esperienzapersonale',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sentiero',
            name='difficoltaMedia',
        ),
        migrations.RemoveField(
            model_name='sentiero',
            name='visite',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
