# Generated by Django 2.2.1 on 2019-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sentieriApp', '0003_auto_20190624_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiero',
            name='altitudineMax',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sentiero',
            name='altitudineMin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sentiero',
            name='discesa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sentiero',
            name='salita',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
