# Generated by Django 2.2.1 on 2019-06-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sentieriApp', '0004_auto_20190624_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='residenza',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='sentieriApp.Citta'),
        ),
    ]
