# Generated by Django 2.2.1 on 2019-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentieriApp', '0006_auto_20190624_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esperienzapersonale',
            options={'verbose_name': 'Esperienza personale', 'verbose_name_plural': 'Esperienze personali'},
        ),
        migrations.AlterModelOptions(
            name='preferito',
            options={'verbose_name': 'Preferito', 'verbose_name_plural': 'Preferiti'},
        ),
        migrations.AddField(
            model_name='sentiero',
            name='partecipanti',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='utente',
            name='eta',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='utente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Uomo'), ('F', 'Donna'), ('A', 'Altro')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='sentiero',
            name='difficoltaMedia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterModelTable(
            name='preferito',
            table='preferito',
        ),
    ]
