# Generated by Django 2.2.1 on 2019-06-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentieriApp', '0007_auto_20190625_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esperienzapersonale',
            name='difficolta',
        ),
        migrations.RemoveField(
            model_name='sentiero',
            name='partecipanti',
        ),
        migrations.AddField(
            model_name='sentiero',
            name='difficolta',
            field=models.ForeignKey(default='E', on_delete=django.db.models.deletion.CASCADE, to='sentieriApp.Difficolta'),
        ),
        migrations.AlterField(
            model_name='sentiero',
            name='difficoltaMedia',
            field=models.IntegerField(),
        ),
    ]
